dynamics: "${include: configs/dynamics/default_dynamics.yaml, unicycle_steer}"

dataset: "/home/me/data/datasets/vc_uniform_samples/horizon_16/gd__unicycle_steer__16"

velocity_network:
  hidden_dim: 512
  n_layers: 3
  activation: "silu"
  init_method: null

preprocess:
  normalization: "std"

training:
  lr: 0.001
  batch_size: 256
  n_epochs: 256
  print_every_step: 2000

n_vis_samples: 1000

output_root: ???
output_name: null  # Will be generated automatically
